### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by HugoAlves** [atika/Ubersicht-GitFinder#1]
I just installed the widget and setted the absolute path, a see Permission denied on the widget, below the url. I've tired different places.
Also i seamed to have some problem with spaces so i couldn't place it under "/Users/nblocal/Library/Application Support/Übersicht" i would way path or file not found and only searching in for "/Users/nblocal/Library/Application"

**Comment by atika** [comment]
Have you tried to put the files in a different folder and check with the terminal if you have the good rights on the file (execution). You can also execute the main script from the command line to see if it's works. 
Maybe the script can't execute from Application Support Folder. For the space on the path try to add an back slash () before the space...

**Comment by HugoAlves** [comment]
ok i fixed the problem with the permissions,
But now I'm getting this errors, is there something I have to install that i probably missed?
![screen shot 2015-08-06 at 14 36 08](https://cloud.githubusercontent.com/assets/1064855/9112733/48424e20-3c48-11e5-82eb-f986b976b2c0.png)

**Comment by atika** [comment]
Have you NodeJS installed?

**Comment by HugoAlves** [comment]
yes version 0.12.7

**Comment by atika** [comment]
Can you paste all the lines from the terminal.

**Comment by HugoAlves** [comment]
how to i run the script? `coffee index.coffee`
I think the problem is i don't have coffeescript installed on this mac I'm gonna install and see if it resolves the problem. I'm surprised other widget work. I'll let you know if that was the problem.

**Comment by atika** [comment]
I tell you to paste the lines from the terminal because I think you execute the JavaScript file directly. The JS file is the compiled version of the coffeescript. Get the path of Node with 

```
which node
```

And next

```
/usr/local/bin/node /path/to/the/script.js
```

**Comment by HugoAlves** [comment]
That appeared to work
    /usr/local/bin/node /Users/nblocal/Desktop/commands/GitFinder.js 

{"gitrepos":[{"path":"/Users/nblocal/Git-Repositories/Apps - android/App Agregadora-Android","name":"App Agregadora Android","branch":"release_app_3","remote":0,"ahead":0,"behind":0,"branches":"9","stash":"1","size":"728M","stats":{"added":0,"modified":1,"untracked":0,"ignored":48},"hash":"10sa0e56c0321e91f0e25cc819af360277983021"}],"prefs":{"backStyle":{"background-color":"rgba(0,0,0,0.3)","border":"solid 1px rgba(255,255,255,0.1)","color":"white"},"applyBackStyle":false,"showMark":true,"showSize":true,"position":"TL|3929","statsAfter":false,"statsBigger":false,"showIgnored":true,"autoFade":false,"autoFadeTimeout":8000}}

the problem seams to be on the index.coffee (i'm having troble installing coffee-script on my mac with npm)

**Comment by atika** [comment]
Yes it works as expected, nothing to do with a problem on index.coffee file or with the script.

```
npm install -g coffee-script
```

After CoffeeScript installation if you execute the coffescript file you get the same JSON result as the Javascript file.

**Comment by HugoAlves** [comment]
running the index.coffee with `coffee index.coffee` return nothing.
running with `/usr/local/bin/node index.coffee` i get:

/Users/nblocal/Library/Application Support/Übersicht/widgets/GitFinder/index.coffee:1
(function (exports, require, module, __filename, __dirname) { # GitFinder Widg
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

i bet i'm doing something really stupid at this point :\

i'm checking the developer console from Ubersicht this is what i can see:

```
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (GitFinder-index-coffee, line 0)
[Error] GitFinder-index-coffee: /Users/nblocal/Desktop/commands/GitFinder.js: line 1: //: is a directory
/Users/nblocal/Desktop/commands/GitFinder.js: line 2: var: command not found
/Users/nblocal/Desktop/commands/GitFinder.js: line 4: syntax error near unexpected token ('
/Users/nblocal/Desktop/commands/GitFinder.js: line 4: exec = require('child_process').exec;'

redraw (main.js, line 404)
(anonymous function) (main.js, line 373)
error (main.js, line 393)
j (jquery.js, line 2)
fireWith (jquery.js, line 2)
x (jquery.js, line 4)
(anonymous function) (jquery.js, line 4)
```

**Comment by atika** [comment]
When you run a coffee script file with `coffee` it execute the file as a NodeJS script. The Javascript is a compiled version of the coffeescript. You have to change the full command and the path on Ubersicht file as explained on the readme I do.

If this worked `/usr/local/bin/node /Users/nblocal/Desktop/commands/GitFinder.js` you put this as the command on the widget.

**Comment by HugoAlves** [comment]
AH! it worked :D
Tks so much for you help. You're the best

**Comment by atika** [comment]
You'are welcome ;) :+1:
