### ISSUE TITLE
SVG icons are not displayed

### ISSUE THREAD

**Issue by juliengdt** [atika/Ubersicht-GitFinder#3]
Hello,

The widgets is fully working, and near my GitFinder.widget, i had my folder "img" with inside all SVGs. 

But the widget doesn't show them (see picture)

Am i missing someting ?

![capture d ecran 2016-06-02 a 10 07 24](https://cloud.githubusercontent.com/assets/6575155/15737985/62ab6dd4-28a9-11e6-9881-79b13582c3b4.png)

Here is the tree of my widget (you cans see "img" folder with svgs)

![capture d ecran 2016-06-02 a 10 10 04](https://cloud.githubusercontent.com/assets/6575155/15738029/94c38446-28a9-11e6-9057-50b661a39e91.png)

**Comment by atika** [comment]
Yes. I recommend to put the "command" scripts outside the widget folder to avoid to be interpreted as a Ubersicht widget script.
The reason why the SVGs images are not displayed is that the URL of each image is absolute into the stylesheet: `GitFinder.widget/img/arrow-up-right.svg` 😉
Place the folder `GitFinder.widget`at the root of your Widget folder, or edit the images paths.

**Comment by juliengdt** [comment]
Oh thanks !! done it works !
