### ISSUE TITLE
Couldn't install 

### ISSUE THREAD

**Issue by yogeshvar** [atika/Ubersicht-GitFinder#4]
@atika  have cloned GitFinder and Copied the widget folder to Ubersicht and Commands to Desktop.
![screen shot 2017-11-22 at 11 47 11 pm](https://user-images.githubusercontent.com/17572818/33143380-b9322f6a-cfdf-11e7-8fa1-59602ce32b6e.png)
`which node` is `/usr/local/bin/node` Node version is v6.10.3

**Comment by atika** [comment]
@yogeshvar I don't think the path `/Users/path/to/Commands` is a valid path on your system... and they are a description of the installation in the README.
Copy the widget folder and the folder containing the command (NodeJS) on your preferred location, then **edit the widget script** to **set the full path of the command** like so:
`command: "/usr/local/bin/node /Users/path/to/Commands/GitFinder.command/GitFinder.js"`
