### ISSUE TITLE
If xcode.app is not installed, endless dialog box nagging occurs

### ISSUE THREAD

**Issue by Scott-Fischer** [atika/Ubersicht-GitFinder#5]
I'm just a web developer so I do not have the xcode app installed- I can get by with the xcode command line tools.

Since I do not have xcode.app installed, I get presented with a pop up dialog box which asks me to locate the xcode launcher. This would be fine if it was a one time thing but it seems to happen very frequently. Maybe an option in the config.json file could be used to disable xcode support?

System is on High Sierra (10.13.4 )
Ubersicht V 1.2 (53)

**Comment by atika** [comment]
You can simply edit the applescript **FinderFolders.scpt** and comment or remove the part that check for Xcode projects.

```
if is_running("Xcode") then
 [...]
end if
```

I added this last time to retrieve Git projects opens in Xcode and I had no solution to avoid applescript to prompt for the path of the app if it is not installed.
